2015-11-24 19:51:10,642 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:34]
2015-11-24 19:59:31,062 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:34]
2015-11-24 20:04:46,775 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:34]
2015-11-24 20:10:43,888 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:34]
2015-11-24 20:19:18,290 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:34]
2015-11-24 20:19:29,193 ERROR: Exception on /index [GET] [in /Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/Users/betty/Desktop/microblog/app/views.py", line 40, in index
    posts=posts)
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/betty/Desktop/microblog/app/templates/base.html", line 28, in template
    {% block content %}
TemplateAssertionError: block 'content' defined twice
2015-11-24 20:19:48,032 ERROR: Exception on /index [GET] [in /Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/Users/betty/Desktop/microblog/app/views.py", line 40, in index
    posts=posts)
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/betty/Desktop/microblog/app/templates/base.html", line 28, in template
    {% block content %}
TemplateAssertionError: block 'content' defined twice
2015-11-24 20:21:04,075 ERROR: Exception on /index [GET] [in /Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/Users/betty/Desktop/microblog/app/views.py", line 40, in index
    posts=posts)
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/betty/Desktop/microblog/app/templates/base.html", line 28, in template
    {% block content %}
TemplateAssertionError: block 'content' defined twice
2015-11-24 20:32:29,425 ERROR: Exception on /index [GET] [in /Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/Users/betty/Desktop/microblog/app/views.py", line 40, in index
    posts=posts)
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/betty/Desktop/microblog/app/templates/base.html", line 28, in template
    {% block content %}
TemplateAssertionError: block 'content' defined twice
2015-11-24 20:32:53,494 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:34]
2015-11-24 20:33:07,268 ERROR: Exception on /index [GET] [in /Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/Users/betty/Desktop/microblog/app/views.py", line 40, in index
    posts=posts)
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/betty/Desktop/microblog/flask/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/betty/Desktop/microblog/app/templates/base.html", line 28, in template
    {% block content %}
TemplateAssertionError: block 'content' defined twice
2015-11-24 21:17:40,384 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:34]
2015-11-24 21:21:41,024 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:34]
2015-12-01 13:02:42,977 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:34]
2015-12-01 13:02:43,570 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:34]
2015-12-01 13:21:36,899 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:34]
2015-12-01 13:22:04,650 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:34]
2015-12-01 13:24:55,917 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:34]
2015-12-01 13:42:13,614 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:34]
2015-12-01 16:01:46,433 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:34]
2015-12-01 16:02:51,630 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:34]
2015-12-01 16:02:52,076 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:34]
2015-12-01 17:10:19,045 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:34]
2015-12-01 17:37:12,915 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:34]
2015-12-01 17:38:10,103 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:34]
2015-12-01 17:38:44,113 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:34]
2015-12-01 17:38:44,572 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:34]
2015-12-01 19:10:13,351 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:34]
2015-12-01 19:21:01,960 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:34]
2015-12-01 19:56:11,030 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:34]
2015-12-02 16:47:27,971 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:34]
2015-12-02 16:47:55,089 INFO: microblog startup [in app/__init__.py:34]
2015-12-02 16:48:57,987 INFO: microblog startup [in app/__init__.py:34]
2015-12-02 16:50:23,106 INFO: microblog startup [in app/__init__.py:34]
2015-12-02 17:32:28,057 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:34]
2015-12-02 17:32:28,681 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:34]
2015-12-02 18:03:04,524 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:36]
2015-12-02 18:05:14,023 INFO: microblog startup [in app/__init__.py:36]
2015-12-02 18:11:02,763 INFO: microblog startup [in app/__init__.py:36]
2015-12-02 18:55:06,886 INFO: microblog startup [in app/__init__.py:36]
2015-12-02 22:59:14,932 INFO: microblog startup [in app/__init__.py:36]
2015-12-02 23:01:01,905 INFO: microblog startup [in app/__init__.py:36]
2015-12-02 23:06:45,963 INFO: microblog startup [in app/__init__.py:36]
2015-12-02 23:11:07,871 INFO: microblog startup [in app/__init__.py:36]
2015-12-02 23:58:31,130 INFO: microblog startup [in app/__init__.py:36]
2015-12-04 12:00:51,727 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:36]
2015-12-04 12:00:52,316 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:36]
2015-12-04 12:16:47,894 INFO: microblog startup [in app/__init__.py:36]
2015-12-04 12:39:33,458 INFO: microblog startup [in app/__init__.py:36]
2015-12-04 14:31:38,932 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:36]
2015-12-04 14:31:39,451 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:36]
2015-12-04 14:35:17,692 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:36]
2015-12-04 14:35:18,096 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:36]
2015-12-04 15:49:59,391 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:36]
2015-12-04 15:49:59,955 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:36]
2015-12-04 15:57:52,673 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:36]
2015-12-04 15:57:53,081 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:36]
2015-12-04 16:15:27,152 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:36]
2015-12-04 16:15:27,621 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:36]
2015-12-04 16:43:05,236 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:36]
2015-12-04 16:43:05,661 INFO: microblog startup [in /Users/betty/Desktop/microblog/app/__init__.py:36]
